version: '0.1'
services:
  web-app:
    image: main-server
    hostname: main-server
    ports:
      - "8080:8080"
  rabbitmq:
    image: rabbitmq:3.8.3-management-alpine
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
  persistence:
    image: postgres:14.2-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret229
    ports:
      - "5432:5432"