<!DOCTYPE html>
<html lang="eng">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <title>Confirm registration</title>
    <style>
        h1 {
            color: #785fa0;
        }
        h2 {
            color: #37ff00;
        }
    </style>
</head>
<body>
<h1>Link:</h1>
<h2><a href="${server_url}/confirm/${confirm_code}">Follow link</a></h2>
</body>
</html>