spring:
  application:
    name: main-service

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${random.value}
    hostname: localhost

server:
  port: 0