POST http://localhost:8080/students/add
Content-Type: application/json

{
  "name": "Egor",
  "surname": "Fedusiv",
  "age": "20",
  "group": "a0001"

}

###

POST http://localhost:8080/students/addAll
Content-Type: application/json


[
  {
    "name": "petr",
    "surname": "petroff",
    "age": "20",
    "group": "a0001"
  },

  {
    "name": "Ivan",
    "surname": "Ivanoff",
    "age": "20",
    "group": "a0001"
  }

]


###

POST http://localhost:8080/signUp
Content-Type: application/json

{

  "email": "foo73bar@gmail.com",
  "username": "Olor",
  "password": "olo&*99"

}


